---
title: "Team"
title-block-style: none
toc: true
---

## Principal Investigator

Federico Pianzola (University of Groningen)

## Associated researchers

Franziska Pannach (University of Groningen)

Andreas van Cranenburgh (University of Groningen)

Tommaso Caselli (University of Groningen)

Simone Rebora (University of Verona)

## Postdoctoral researchers

We'll be hiring in 2025

## PhDs

Noa Visser Solissa (University of Groningen)

Xiaoyan Yang (University of Groningen)

Ze Yu (University of Groningen)

And [we're open to collaborations!](/news/collaborations/)

## Other contributors

Michiel van der Ree (University of Groningen)

Luca Scotti (University of Bologna)

Edu Vallejo (University of Groningen, The University of the Basque Country)

Ingo Börner (University of Potsdam)

## Scientific Advisors

Alberto Acerbi (University of Trento)

Evelyn Gius (Technical University Darmstadt)

Folgert Karsdorp (KNAW Meertens Institute)

Nina Tahmasebi (University of Gothenburg)

Jamie Tehrani (Durham University)
